# Autogenerated wrapper script for gb_jll for aarch64-linux-musl
export libgb

using GMP_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("gb")
JLLWrappers.@declare_library_product(libgb, "libgb.so.0")
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libgb,
        "lib/libgb.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
