# Autogenerated wrapper script for gb_jll for x86_64-apple-darwin
export libgb

using GMP_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("gb")
JLLWrappers.@declare_library_product(libgb, "@rpath/libgb.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libgb,
        "lib/libgb.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
